name: SWC
author: SpleefLeague
authors: [Joba, Akaiyo, Manuman, JoshK_]
main: com.spleefleague.swc.SWC
version: 1.0
depend: [SpleefLeagueCore]
commands:    
    ready:
        usage: /<command>
    reset:
        usage: /<command>
    report:
        usage: /<command>
    matches:
        usage: /<command>